CREATE DATABASE SODO_ANDROID
USE SODO_ANDROID
GO

CREATE TABLE VOCABULARY
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	CAUDE NVARCHAR(500),
	DAPANA NVARCHAR(300),
	DAPANB NVARCHAR(300),
	DAPANC NVARCHAR(300),
	DAPAND NVARCHAR(300),
	DAPANDUNG NVARCHAR(10),
)

CREATE TABLE FAMILYWORD
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	CAUDE NVARCHAR(500),
	DAPANA NVARCHAR(300),
	DAPANB NVARCHAR(300),
	DAPANC NVARCHAR(300),
	DAPAND NVARCHAR(300),
	DAPANDUNG NVARCHAR(10),
)

CREATE TABLE GRAMMAR
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	LOAINGUPHAP NVARCHAR(200),
	CAUDE NVARCHAR(500),
	DAPANA NVARCHAR(300),
	DAPANB NVARCHAR(300),
	DAPANC NVARCHAR(300),
	DAPAND NVARCHAR(300),
	DAPANDUNG NVARCHAR(10),
)

CREATE TABLE CHANGESENTENCES
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	LOAICAU NVARCHAR(200),
	CAUDE NVARCHAR(500),
	DAPANA NVARCHAR(300),
	DAPANB NVARCHAR(300),
	DAPANC NVARCHAR(300),
	DAPAND NVARCHAR(300),
	DAPANDUNG NVARCHAR(10),
)

CREATE TABLE LISTENING
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDAUDIO NVARCHAR(200),
	CAUDE NVARCHAR(500),
	DAPANA NVARCHAR(300),
	DAPANB NVARCHAR(300),
	DAPANC NVARCHAR(300),
	DAPAND NVARCHAR(300),
	DAPANDUNG NVARCHAR(10),
)

CREATE TABLE BAITHITHU
(
	IDBAITHITHU INT PRIMARY KEY,
	TENDETHI NVARCHAR(200),
)

CREATE TABLE PART1
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDAUDIO NVARCHAR(200),
	HINH NVARCHAR (200),
	DAPANA NVARCHAR(300),
	DAPANB NVARCHAR(300),
	DAPANC NVARCHAR(300),
	DAPAND NVARCHAR(300),
	DAPANCHON NVARCHAR(10),
	DAPANDUNG NVARCHAR(10),
	IDBAITHITHU INT,
)

CREATE TABLE PART2
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDAUDIO NVARCHAR(200),
	CAUDE NVARCHAR (500),
	DAPANA NVARCHAR(300),
	DAPANB NVARCHAR(300),
	DAPANC NVARCHAR(300),
	DAPAND NVARCHAR(300),
	DAPANCHON NVARCHAR(10),
	DAPANDUNG NVARCHAR(10),
	IDBAITHITHU INT,
)

CREATE TABLE PART3
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDAUDIO NVARCHAR(200),
	CAUDE NVARCHAR (500),
	DAPANA NVARCHAR(300),
	DAPANB NVARCHAR(300),
	DAPANC NVARCHAR(300),
	DAPAND NVARCHAR(300),
	DAPANCHON NVARCHAR(10),
	DAPANDUNG NVARCHAR(10),
	IDBAITHITHU INT,
)

CREATE TABLE PART4
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDAUDIO NVARCHAR(200),
	CAUDE NVARCHAR (500),
	DAPANA NVARCHAR(300),
	DAPANB NVARCHAR(300),
	DAPANC NVARCHAR(300),
	DAPAND NVARCHAR(300),
	DAPANCHON NVARCHAR(10),
	DAPANDUNG NVARCHAR(10),
	IDBAITHITHU INT,
)

CREATE TABLE PART5
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	CAUDE NVARCHAR (500),
	DAPANA NVARCHAR(300),
	DAPANB NVARCHAR(300),
	DAPANC NVARCHAR(300),
	DAPAND NVARCHAR(300),
	DAPANCHON NVARCHAR(10),
	DAPANDUNG NVARCHAR(10),
	IDBAITHITHU INT,
)

CREATE TABLE PART6
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	CAUDE NVARCHAR (500),
	DAPANA NVARCHAR(300),
	DAPANB NVARCHAR(300),
	DAPANC NVARCHAR(300),
	DAPAND NVARCHAR(300),
	DAPANCHON NVARCHAR(10),
	DAPANDUNG NVARCHAR(10),
	IDBAITHITHU INT,
)

CREATE TABLE PART7
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	DOANVAN NVARCHAR (MAX),
	CAUDE NVARCHAR (500),
	DAPANA NVARCHAR(300),
	DAPANB NVARCHAR(300),
	DAPANC NVARCHAR(300),
	DAPAND NVARCHAR(300),
	DAPANCHON NVARCHAR(10),
	DAPANDUNG NVARCHAR(10),
	IDBAITHITHU INT,
)

CREATE TABLE DANHMUCTU
(
	IDDANHMUCTU INT PRIMARY KEY,
	TENDANHMUC NVARCHAR (500),
)

CREATE TABLE TUVUNG
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TU NVARCHAR(500),
	LOAITU NVARCHAR(500),
	NGHIA NVARCHAR(500),
	IDDANHMUCTU INT,
)

ALTER TABLE PART1
	ADD CONSTRAINT FK_PART1 FOREIGN KEY (IDBAITHITHU) REFERENCES BAITHITHU(IDBAITHITHU)

ALTER TABLE PART2
	ADD CONSTRAINT FK_PART2 FOREIGN KEY (IDBAITHITHU) REFERENCES BAITHITHU(IDBAITHITHU)

ALTER TABLE PART3
	ADD CONSTRAINT FK_PART3 FOREIGN KEY (IDBAITHITHU) REFERENCES BAITHITHU(IDBAITHITHU)

ALTER TABLE PART4
	ADD CONSTRAINT FK_PART4 FOREIGN KEY (IDBAITHITHU) REFERENCES BAITHITHU(IDBAITHITHU)

ALTER TABLE PART5
	ADD CONSTRAINT FK_PART5 FOREIGN KEY (IDBAITHITHU) REFERENCES BAITHITHU(IDBAITHITHU)

ALTER TABLE PART6
	ADD CONSTRAINT FK_PART6 FOREIGN KEY (IDBAITHITHU) REFERENCES BAITHITHU(IDBAITHITHU)

ALTER TABLE PART7
	ADD CONSTRAINT FK_PART7 FOREIGN KEY (IDBAITHITHU) REFERENCES BAITHITHU(IDBAITHITHU)

ALTER TABLE TUVUNG
	ADD CONSTRAINT FK_DMT FOREIGN KEY (IDDANHMUCTU) REFERENCES DANHMUCTU(IDDANHMUCTU)